# Generated by Django 4.2 on 2024-07-24 02:50

import app.models
import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "name",
                    models.CharField(
                        default="", help_text="Name of Tag", max_length=100
                    ),
                ),
                (
                    "id_hash",
                    models.CharField(
                        blank=True,
                        default=app.models.tagHash,
                        help_text="Unique ID for the tag",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name of Product",
                        max_length=1000,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of Product (Displayed for Featured Products)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="", upload_to="assets/products"
                    ),
                ),
                ("image_alt", models.CharField(blank=True, default="", max_length=100)),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                ("price", models.CharField(blank=True, default="", max_length=100)),
                (
                    "url_hash",
                    models.SlugField(
                        blank=True,
                        default=app.models.productHash,
                        help_text="Unique URL path for the Product",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_featured", models.BooleanField(blank=True, default=False)),
                ("is_published", models.BooleanField(blank=True, default=False)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("tags", models.ManyToManyField(to="app.tag")),
            ],
            options={
                "ordering": (
                    "name",
                    "url_hash",
                    "price",
                    "is_published",
                    "is_featured",
                    "created_at",
                    "published_at",
                ),
            },
        ),
    ]
