# Generated by Django 4.2 on 2024-07-24 03:10

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="url_hash",
            field=models.SlugField(
                blank=True,
                default=app.models.productHash,
                help_text="Unique URL path for the Product",
                max_length=6,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
