# Generated by Django 4.2 on 2024-07-24 04:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_product_url_hash"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ("name", "id_hash")},
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
